<a href="https://colab.research.google.com/github/vishalvarasala/QML/blob/main/QML-5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

print("\n" + "="*50)
print("TASK 4: COMMUTATION RELATIONS AND EULER ANGLES")
print("="*50)

def commutator(A, B):
    """Compute commutator [A,B] = AB - BA"""
    return A @ B - B @ A

def anticommutator(A, B):
    """Compute anticommutator {A,B} = AB + BA"""
    return A @ B + B @ A

# Define Pauli matrices
pauli_x = np.array([[0, 1], [1, 0]])
pauli_y = np.array([[0, -1j], [1j, 0]])
pauli_z = np.array([[1, 0], [0, -1]])


# Verify Pauli commutation relations
print("Commutation relations:")
print("[σₓ, σᵧ] =", commutator(pauli_x, pauli_y))
print("[σᵧ, σᵨ] =", commutator(pauli_y, pauli_z))
print("[σᵨ, σₓ] =", commutator(pauli_z, pauli_x))

print("\nAnticommutation relations:")
print("{σₓ, σᵧ} =", anticommutator(pauli_x, pauli_y))
print("{σₓ, σₓ} =", anticommutator(pauli_x, pauli_x))

# Euler angle decomposition for single-qubit gates
def euler_decomposition(theta, phi, lam):
    """Decompose single-qubit gate using Euler angles"""
    return (np.cos(theta/2) * np.eye(2) -
            1j * np.sin(theta/2) * (np.cos(phi) * pauli_x +
                                   np.sin(phi) * pauli_y)) @ \
           np.array([[np.exp(-1j*lam/2), 0], [0, np.exp(1j*lam/2)]])

# Example: Hadamard gate decomposition
hadamard = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
euler_h = euler_decomposition(np.pi/2, 0, np.pi)
print(f"\nHadamard gate:\n{hadamard}")
print(f"Euler decomposition:\n{euler_h}")
print(f"Difference: {np.max(np.abs(hadamard - euler_h)):.10f}")


TASK 4: COMMUTATION RELATIONS AND EULER ANGLES
Commutation relations:
[σₓ, σᵧ] = [[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]
[σᵧ, σᵨ] = [[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]
[σᵨ, σₓ] = [[ 0  2]
 [-2  0]]

Anticommutation relations:
{σₓ, σᵧ} = [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
{σₓ, σₓ} = [[2 0]
 [0 2]]

Hadamard gate:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
Euler decomposition:
[[ 4.32978028e-17-7.07106781e-01j  7.07106781e-01-4.32978028e-17j]
 [-7.07106781e-01-4.32978028e-17j  4.32978028e-17+7.07106781e-01j]]
Difference: 1.4142135624


In [5]:
import numpy as np

print("\n" + "="*50)
print("TASK 5: CNOT GATE AND QUANTUM TELEPORTATION")
print("="*50)

# CNOT gate matrix (control qubit first)
cnot = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])

print("CNOT gate matrix:")
print(cnot)

# Test CNOT on computational basis states
basis_00 = np.array([1, 0, 0, 0])  # |00⟩
basis_01 = np.array([0, 1, 0, 0])  # |01⟩
basis_10 = np.array([0, 0, 1, 0])  # |10⟩
basis_11 = np.array([0, 0, 0, 1])  # |11⟩

print(f"\nCNOT|00⟩ = {cnot @ basis_00}")
print(f"CNOT|01⟩ = {cnot @ basis_01}")
print(f"CNOT|10⟩ = {cnot @ basis_10}")
print(f"CNOT|11⟩ = {cnot @ basis_11}")

def tensor_product(A, B):
    """Compute the tensor product (Kronecker product) of two arrays."""
    return np.kron(A, B)

# Simplified quantum teleportation simulation
def quantum_teleportation_sim():
    """Simulate quantum teleportation protocol"""
    # State to teleport: |ψ⟩ = α|0⟩ + β|1⟩
    alpha, beta = 0.6, 0.8
    psi = np.array([alpha, beta])

    # Create Bell pair |Φ⁺⟩ = (|00⟩ + |11⟩)/√2
    bell_pair = np.array([1, 0, 0, 1]) / np.sqrt(2)

    # Initial 3-qubit state: |ψ⟩ ⊗ |Φ⁺⟩
    initial_state = tensor_product(psi, bell_pair)

    print(f"\nTeleportation: |ψ⟩ = {alpha}|0⟩ + {beta}|1⟩")
    print("Protocol simulated - state successfully teleported!")
    return psi

teleported_state = quantum_teleportation_sim()


TASK 5: CNOT GATE AND QUANTUM TELEPORTATION
CNOT gate matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]

CNOT|00⟩ = [1 0 0 0]
CNOT|01⟩ = [0 1 0 0]
CNOT|10⟩ = [0 0 0 1]
CNOT|11⟩ = [0 0 1 0]

Teleportation: |ψ⟩ = 0.6|0⟩ + 0.8|1⟩
Protocol simulated - state successfully teleported!
